namespace StemCode.Application.Models;

public sealed record SessionEventRecord(
    DateTimeOffset TimestampUtc,
    string SectionId,
    string? ParentSessionId,
    string EventType,
    string AgentProfileName,
    string ModelId,
    string WorkingDirectory,
    string? Text = null,
    string? ToolCallId = null,
    string? ToolName = null,
    string? ToolArgumentsJson = null,
    string? ToolStatus = null,
    string? ToolMessage = null,
    string? ToolResultJson = null,
    string? ErrorType = null,
    long? EventSequenceId = null,
    string? TurnId = null,
    int? TurnIndex = null,
    string? StepId = null,
    int? StepIndex = null,
    string? ModelRequestId = null,
    string? AssistantMessageId = null,
    string? ToolResultId = null,
    string? ParentCallId = null,
    string? Source = null,
    string? SystemPrompt = null,
    string? ToolsJson = null,
    string? ToolSchemaJson = null,
    string? RequestOptionsJson = null,
    string? InputJson = null,
    string? OutputJson = null,
    string? ThinkingJson = null,
    string? RawJson = null,
    string? Status = null,
    string? ErrorCode = null,
    int? RetryNumber = null,
    int? MaxRetries = null,
    int? RetryDelayMs = null,
    int? InputTokens = null,
    int? CacheReadTokens = null,
    int? CacheWriteTokens = null,
    int? OutputTokens = null,
    int? ReasoningTokens = null,
    DateTimeOffset? RequestStartedAtUtc = null,
    DateTimeOffset? FirstTokenAtUtc = null,
    DateTimeOffset? CompletedAtUtc = null,
    double? TotalDurationMs = null,
    double? TtftMs = null,
    double? GenerationDurationMs = null,
    double? TokensPerSecond = null,
    bool? IsPartial = null,
    bool? IsRunning = null,
    bool? Interrupted = null,
    string? Summary = null,
    int? ItemsReplaced = null,
    int? TokensReplaced = null);
